#!/usr/bin/env bash
echo "package.json"
cat package.json 
echo "============================="
echo "index.html"
cat index.html
echo "============================="
echo "src/main.jsx"
cat "src/main.jsx"
echo "============================="
echo "src/App.jsx"
cat "src/App.jsx"
echo "============================="
echo "src/global.css"
cat "src/global.css"
echo "============================="
echo "src/components/Fox.jsx"
cat "src/components/Fox.jsx"
echo "============================="
